### ISSUE TITLE
Multiple features not working (F-15C)

### ISSUE THREAD

**Issue by ZorkaA** [Zaretto/fg-aircraft#169] opened 2023-01-02 09:16 UTC
Currently reported:
- Gear retraction not working 
- AB flames not showing up (thrust increase seems to still be present though)
- MLW/MAW do not display on-screen

Reinstalling a fresh version of both the aircraft and FG do not help. 

These issues have been confirmed by others as well as myself.

**Comment by Megaf** [comment] 2023-01-03 19:25
> * Gear retraction not working

Indeed, can't operate the landing gear with the keyboard shortcut, but the lever in the cockpit still retracts it.

> * AB flames not showing up (thrust increase seems to still be present though)

Confirmed

> * MLW/MAW do not display on-screen

I'm not sure what you mean.


Edit: By the way, affects the F-15D as well.

**Comment by Zaretto** [comment] 2023-01-04 15:47
Using the release 1.12 branch I can confirm that 

* Gear retraction from the keyboard works (2020.3.12, 2020.4)
* ALS Afterburner effects not working.

Assuming that MLW means missile lock warning and MAW means missile approach warning this is something that I will pass over to @NikolaiVChr to investigate should he have available time.

**Comment by NikolaiVChr** [comment] 2023-01-04 16:14
Do you see the MLW/MAW in the eventlog after the battle or are they missing from that also?

**Comment by Megaf** [comment] 2023-01-04 19:44
> * ALS Afterburner effects not working.

Not working at all, ALS on and off.

> * Gear retraction from the keyboard works (2020.3.12, 2020.4)

Assuming it worked on `2020.3.12`, it broke after that. Doesn't work on .17 and .18.

**Comment by ZorkaA** [comment] 2023-01-04 20:37
> Do you see the MLW/MAW in the eventlog after the battle or are they missing from that also?

They show up in the event log. They do not display on-screen however, which could suggest something missing in the config of `damage.nas`.

**Comment by NikolaiVChr** [comment] 2023-01-04 21:24
They are yellow, so blend in a bit with the sky, is there a chance you just
missed them?
And which missile was approaching you? Only RB99, AIM-120 gives MAW
warnings. Rest only give MLW when you are very very close to the
aircraft firing them.
Oh, and half the SAMs give MAW too.

**Comment by NikolaiVChr** [comment] 2023-01-04 21:24
Oh, nevermind, I forgot you saw them in the log, hmmm. The F15 seems to be
correct configured to show them.

**Comment by Zaretto** [comment] 2024-01-30 18:28
Closing this because it works for me.

**Closed as completed by Zaretto** 2024-01-30 18:28 UTC
